name: Upload some files to Qiniu and Aws when they change
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/test.yml
      - bin/*
      - lib/*
jobs:
  run:
    name: Build and Upload
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        ocaml-version:
          - 4.07.1
    steps:
      - uses: actions/checkout@master
      - uses: avsm/setup-ocaml@master
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Build
        run: |
          opam exec -- dune build
          cp ./_build/default/bin/cloud_assets_utils.exe /usr/local/bin/cloud_assets_utils

      - name: Configure qshell
        run: |
          curl http://devtools.qiniu.com/qshell-linux-x64-v2.4.1.zip -o qshell.zip
          unzip qshell.zip
          mv qshell-linux-x64-v2.4.1 /usr/local/bin/qshell
          qshell account ${{ secrets.QINIU_ACCESS_KEY }} ${{ secrets.QINIU_SECRET_KEY }} test

      - name: configure awscli
        run: |
          pip3 install awscli
          printf "%s\n" ${{ secrets.AWS_ACCESS_KEY }} ${{ secrets.AWS_SECRET_KEY }} ${{ secrets.AWS_REGION }} "json" | aws configure

      - name: Upload
        run: |
          cloud_assets_utils verify-and-sync -qiniu true -qiniu-bucket ${{ secrets.QINIU_BUCKET_NAME }} -aws true -aws-bucket ${{ secrets.AWS_BUCKET_NAME }} .github
          cloud_assets_utils verify-and-sync -qiniu true -qiniu-bucket ${{ secrets.QINIU_BUCKET_NAME }} -aws true -aws-bucket ${{ secrets.AWS_BUCKET_NAME }} bin
          cloud_assets_utils verify-and-sync -qiniu true -qiniu-bucket ${{ secrets.QINIU_BUCKET_NAME }} -aws true -aws-bucket ${{ secrets.AWS_BUCKET_NAME }} lib
